/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { AreaRolePermission, Prisma } from '@zenstackhq/runtime/models';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateAreaRolePermission(
  options?: Omit<UseMutationOptions<AreaRolePermission | undefined, DefaultError, Prisma.AreaRolePermissionCreateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AreaRolePermissionCreateArgs, DefaultError, AreaRolePermission, true>(
    'AreaRolePermission',
    'POST',
    `${endpoint}/areaRolePermission/create`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AreaRolePermissionCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.AreaRolePermissionCreateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.AreaRolePermissionCreateArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyAreaRolePermission(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AreaRolePermissionCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AreaRolePermissionCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'AreaRolePermission',
    'POST',
    `${endpoint}/areaRolePermission/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AreaRolePermissionCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AreaRolePermissionCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AreaRolePermissionCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindManyArgs,
  TQueryFnData = Array<Prisma.AreaRolePermissionGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findMany`, args, options, fetch);
}

export function useInfiniteFindManyAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindManyArgs,
  TQueryFnData = Array<Prisma.AreaRolePermissionGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findMany`, args, options, fetch);
}

export function useSuspenseFindManyAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindManyArgs,
  TQueryFnData = Array<Prisma.AreaRolePermissionGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindManyArgs,
  TQueryFnData = Array<Prisma.AreaRolePermissionGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findMany`, args, options, fetch);
}

export function useFindUniqueAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindUniqueArgs,
  TQueryFnData = Prisma.AreaRolePermissionGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindUniqueArgs,
  TQueryFnData = Prisma.AreaRolePermissionGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findUnique`, args, options, fetch);
}

export function useFindFirstAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindFirstArgs,
  TQueryFnData = Prisma.AreaRolePermissionGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionFindFirstArgs,
  TQueryFnData = Prisma.AreaRolePermissionGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/findFirst`, args, options, fetch);
}

export function useUpdateAreaRolePermission(
  options?: Omit<UseMutationOptions<AreaRolePermission | undefined, DefaultError, Prisma.AreaRolePermissionUpdateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AreaRolePermissionUpdateArgs, DefaultError, AreaRolePermission, true>(
    'AreaRolePermission',
    'PUT',
    `${endpoint}/areaRolePermission/update`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AreaRolePermissionUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.AreaRolePermissionUpdateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.AreaRolePermissionUpdateArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyAreaRolePermission(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AreaRolePermissionUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AreaRolePermissionUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'AreaRolePermission',
    'PUT',
    `${endpoint}/areaRolePermission/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AreaRolePermissionUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AreaRolePermissionUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AreaRolePermissionUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertAreaRolePermission(
  options?: Omit<UseMutationOptions<AreaRolePermission | undefined, DefaultError, Prisma.AreaRolePermissionUpsertArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AreaRolePermissionUpsertArgs, DefaultError, AreaRolePermission, true>(
    'AreaRolePermission',
    'POST',
    `${endpoint}/areaRolePermission/upsert`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AreaRolePermissionUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.AreaRolePermissionUpsertArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.AreaRolePermissionUpsertArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteAreaRolePermission(
  options?: Omit<UseMutationOptions<AreaRolePermission | undefined, DefaultError, Prisma.AreaRolePermissionDeleteArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AreaRolePermissionDeleteArgs, DefaultError, AreaRolePermission, true>(
    'AreaRolePermission',
    'DELETE',
    `${endpoint}/areaRolePermission/delete`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AreaRolePermissionDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.AreaRolePermissionDeleteArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.AreaRolePermissionDeleteArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AreaRolePermission, Prisma.AreaRolePermissionGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyAreaRolePermission(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AreaRolePermissionDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AreaRolePermissionDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'AreaRolePermission',
    'DELETE',
    `${endpoint}/areaRolePermission/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AreaRolePermissionDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AreaRolePermissionDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AreaRolePermissionDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionAggregateArgs,
  TQueryFnData = Prisma.GetAreaRolePermissionAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionAggregateArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionAggregateArgs,
  TQueryFnData = Prisma.GetAreaRolePermissionAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionAggregateArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/aggregate`, args, options, fetch);
}

export function useGroupByAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AreaRolePermissionGroupByArgs['orderBy'] } : { orderBy?: Prisma.AreaRolePermissionGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.AreaRolePermissionGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.AreaRolePermissionGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.AreaRolePermissionGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.AreaRolePermissionGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AreaRolePermissionGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AreaRolePermissionGroupByArgs['orderBy'] } : { orderBy?: Prisma.AreaRolePermissionGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.AreaRolePermissionGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.AreaRolePermissionGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.AreaRolePermissionGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.AreaRolePermissionGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AreaRolePermissionGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/groupBy`, args, options, fetch);
}

export function useCountAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AreaRolePermissionCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/count`, args, options, fetch);
}

export function useSuspenseCountAreaRolePermission<
  TArgs extends Prisma.AreaRolePermissionCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AreaRolePermissionCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AreaRolePermissionCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/count`, args, options, fetch);
}

export function useCheckAreaRolePermission<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { createdBy?: string; modifiedBy?: string; tenantId?: string; id?: string; isActive?: boolean; areaRoleId?: string; permissionId?: string } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('AreaRolePermission', `${endpoint}/areaRolePermission/check`, args, options, fetch);
}
