/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { AssignmentCategoryForm, Prisma } from '@prisma/client';
import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateAssignmentCategoryForm(
  options?: Omit<UseMutationOptions<AssignmentCategoryForm | undefined, DefaultError, Prisma.AssignmentCategoryFormCreateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AssignmentCategoryFormCreateArgs, DefaultError, AssignmentCategoryForm, true>(
    'AssignmentCategoryForm',
    'POST',
    `${endpoint}/assignmentCategoryForm/create`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AssignmentCategoryFormCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormCreateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormCreateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyAssignmentCategoryForm(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AssignmentCategoryFormCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AssignmentCategoryFormCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'AssignmentCategoryForm',
    'POST',
    `${endpoint}/assignmentCategoryForm/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AssignmentCategoryFormCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindManyArgs,
  TQueryFnData = Array<Prisma.AssignmentCategoryFormGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findMany`, args, options, fetch);
}

export function useInfiniteFindManyAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindManyArgs,
  TQueryFnData = Array<Prisma.AssignmentCategoryFormGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findMany`, args, options, fetch);
}

export function useSuspenseFindManyAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindManyArgs,
  TQueryFnData = Array<Prisma.AssignmentCategoryFormGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindManyArgs,
  TQueryFnData = Array<Prisma.AssignmentCategoryFormGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findMany`, args, options, fetch);
}

export function useFindUniqueAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindUniqueArgs,
  TQueryFnData = Prisma.AssignmentCategoryFormGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindUniqueArgs,
  TQueryFnData = Prisma.AssignmentCategoryFormGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findUnique`, args, options, fetch);
}

export function useFindFirstAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindFirstArgs,
  TQueryFnData = Prisma.AssignmentCategoryFormGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormFindFirstArgs,
  TQueryFnData = Prisma.AssignmentCategoryFormGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/findFirst`, args, options, fetch);
}

export function useUpdateAssignmentCategoryForm(
  options?: Omit<UseMutationOptions<AssignmentCategoryForm | undefined, DefaultError, Prisma.AssignmentCategoryFormUpdateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AssignmentCategoryFormUpdateArgs, DefaultError, AssignmentCategoryForm, true>(
    'AssignmentCategoryForm',
    'PUT',
    `${endpoint}/assignmentCategoryForm/update`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AssignmentCategoryFormUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormUpdateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormUpdateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyAssignmentCategoryForm(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AssignmentCategoryFormUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AssignmentCategoryFormUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'AssignmentCategoryForm',
    'PUT',
    `${endpoint}/assignmentCategoryForm/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AssignmentCategoryFormUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertAssignmentCategoryForm(
  options?: Omit<UseMutationOptions<AssignmentCategoryForm | undefined, DefaultError, Prisma.AssignmentCategoryFormUpsertArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AssignmentCategoryFormUpsertArgs, DefaultError, AssignmentCategoryForm, true>(
    'AssignmentCategoryForm',
    'POST',
    `${endpoint}/assignmentCategoryForm/upsert`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AssignmentCategoryFormUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormUpsertArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormUpsertArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteAssignmentCategoryForm(
  options?: Omit<UseMutationOptions<AssignmentCategoryForm | undefined, DefaultError, Prisma.AssignmentCategoryFormDeleteArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AssignmentCategoryFormDeleteArgs, DefaultError, AssignmentCategoryForm, true>(
    'AssignmentCategoryForm',
    'DELETE',
    `${endpoint}/assignmentCategoryForm/delete`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AssignmentCategoryFormDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormDeleteArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormDeleteArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, AssignmentCategoryForm, Prisma.AssignmentCategoryFormGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyAssignmentCategoryForm(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AssignmentCategoryFormDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.AssignmentCategoryFormDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'AssignmentCategoryForm',
    'DELETE',
    `${endpoint}/assignmentCategoryForm/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AssignmentCategoryFormDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AssignmentCategoryFormDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormAggregateArgs,
  TQueryFnData = Prisma.GetAssignmentCategoryFormAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormAggregateArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormAggregateArgs,
  TQueryFnData = Prisma.GetAssignmentCategoryFormAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormAggregateArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/aggregate`, args, options, fetch);
}

export function useGroupByAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AssignmentCategoryFormGroupByArgs['orderBy'] } : { orderBy?: Prisma.AssignmentCategoryFormGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.AssignmentCategoryFormGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.AssignmentCategoryFormGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.AssignmentCategoryFormGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.AssignmentCategoryFormGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AssignmentCategoryFormGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AssignmentCategoryFormGroupByArgs['orderBy'] } : { orderBy?: Prisma.AssignmentCategoryFormGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.AssignmentCategoryFormGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.AssignmentCategoryFormGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.AssignmentCategoryFormGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.AssignmentCategoryFormGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AssignmentCategoryFormGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/groupBy`, args, options, fetch);
}

export function useCountAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AssignmentCategoryFormCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/count`, args, options, fetch);
}

export function useSuspenseCountAssignmentCategoryForm<
  TArgs extends Prisma.AssignmentCategoryFormCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AssignmentCategoryFormCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignmentCategoryFormCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/count`, args, options, fetch);
}

export function useCheckAssignmentCategoryForm<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { createdBy?: string; updatedBy?: string; tenantId?: string; id?: string; isActive?: boolean; categoryId?: string; formId?: string } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('AssignmentCategoryForm', `${endpoint}/assignmentCategoryForm/check`, args, options, fetch);
}
