/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, AssignationHierarchyLevel } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateAssignationHierarchyLevel(options?: Omit<(UseMutationOptions<(AssignationHierarchyLevel | undefined), DefaultError, Prisma.AssignationHierarchyLevelCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AssignationHierarchyLevelCreateArgs, DefaultError, AssignationHierarchyLevel, true>('AssignationHierarchyLevel', 'POST', `${endpoint}/assignationHierarchyLevel/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AssignationHierarchyLevelCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyAssignationHierarchyLevel(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AssignationHierarchyLevelCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AssignationHierarchyLevelCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('AssignationHierarchyLevel', 'POST', `${endpoint}/assignationHierarchyLevel/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AssignationHierarchyLevelCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.AssignationHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findMany`, args, options, fetch);
}

export function useInfiniteFindManyAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.AssignationHierarchyLevelGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findMany`, args, options, fetch);
}

export function useSuspenseFindManyAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.AssignationHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.AssignationHierarchyLevelGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findMany`, args, options, fetch);
}

export function useFindUniqueAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindUniqueArgs, TQueryFnData = Prisma.AssignationHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindUniqueArgs, TQueryFnData = Prisma.AssignationHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findUnique`, args, options, fetch);
}

export function useFindFirstAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindFirstArgs, TQueryFnData = Prisma.AssignationHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelFindFirstArgs, TQueryFnData = Prisma.AssignationHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/findFirst`, args, options, fetch);
}

export function useUpdateAssignationHierarchyLevel(options?: Omit<(UseMutationOptions<(AssignationHierarchyLevel | undefined), DefaultError, Prisma.AssignationHierarchyLevelUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AssignationHierarchyLevelUpdateArgs, DefaultError, AssignationHierarchyLevel, true>('AssignationHierarchyLevel', 'PUT', `${endpoint}/assignationHierarchyLevel/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AssignationHierarchyLevelUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyAssignationHierarchyLevel(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AssignationHierarchyLevelUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AssignationHierarchyLevelUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('AssignationHierarchyLevel', 'PUT', `${endpoint}/assignationHierarchyLevel/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AssignationHierarchyLevelUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertAssignationHierarchyLevel(options?: Omit<(UseMutationOptions<(AssignationHierarchyLevel | undefined), DefaultError, Prisma.AssignationHierarchyLevelUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AssignationHierarchyLevelUpsertArgs, DefaultError, AssignationHierarchyLevel, true>('AssignationHierarchyLevel', 'POST', `${endpoint}/assignationHierarchyLevel/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AssignationHierarchyLevelUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteAssignationHierarchyLevel(options?: Omit<(UseMutationOptions<(AssignationHierarchyLevel | undefined), DefaultError, Prisma.AssignationHierarchyLevelDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AssignationHierarchyLevelDeleteArgs, DefaultError, AssignationHierarchyLevel, true>('AssignationHierarchyLevel', 'DELETE', `${endpoint}/assignationHierarchyLevel/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AssignationHierarchyLevelDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, AssignationHierarchyLevel, Prisma.AssignationHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyAssignationHierarchyLevel(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.AssignationHierarchyLevelDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.AssignationHierarchyLevelDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('AssignationHierarchyLevel', 'DELETE', `${endpoint}/assignationHierarchyLevel/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.AssignationHierarchyLevelDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.AssignationHierarchyLevelDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelAggregateArgs, TQueryFnData = Prisma.GetAssignationHierarchyLevelAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelAggregateArgs, TQueryFnData = Prisma.GetAssignationHierarchyLevelAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/aggregate`, args, options, fetch);
}

export function useGroupByAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AssignationHierarchyLevelGroupByArgs['orderBy'] } : { orderBy?: Prisma.AssignationHierarchyLevelGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.AssignationHierarchyLevelGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.AssignationHierarchyLevelGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.AssignationHierarchyLevelGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.AssignationHierarchyLevelGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AssignationHierarchyLevelGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AssignationHierarchyLevelGroupByArgs['orderBy'] } : { orderBy?: Prisma.AssignationHierarchyLevelGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.AssignationHierarchyLevelGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.AssignationHierarchyLevelGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.AssignationHierarchyLevelGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.AssignationHierarchyLevelGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.AssignationHierarchyLevelGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/groupBy`, args, options, fetch);
}

export function useCountAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AssignationHierarchyLevelCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/count`, args, options, fetch);
}

export function useSuspenseCountAssignationHierarchyLevel<TArgs extends Prisma.AssignationHierarchyLevelCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.AssignationHierarchyLevelCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.AssignationHierarchyLevelCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/count`, args, options, fetch);
}

export function useCheckAssignationHierarchyLevel<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; description?: string; createdBy?: string; modifiedBy?: string; tenantId?: string; hierarchyId?: string; position?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('AssignationHierarchyLevel', `${endpoint}/assignationHierarchyLevel/check`, args, options, fetch);
}
