/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, DataroomViewerGroupAccessControls } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateDataroomViewerGroupAccessControls(options?: Omit<(UseMutationOptions<(DataroomViewerGroupAccessControls | undefined), DefaultError, Prisma.DataroomViewerGroupAccessControlsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataroomViewerGroupAccessControlsCreateArgs, DefaultError, DataroomViewerGroupAccessControls, true>('DataroomViewerGroupAccessControls', 'POST', `${endpoint}/dataroomViewerGroupAccessControls/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataroomViewerGroupAccessControlsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyDataroomViewerGroupAccessControls(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DataroomViewerGroupAccessControlsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataroomViewerGroupAccessControlsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('DataroomViewerGroupAccessControls', 'POST', `${endpoint}/dataroomViewerGroupAccessControls/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataroomViewerGroupAccessControlsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindManyArgs, TQueryFnData = Array<Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findMany`, args, options, fetch);
}

export function useInfiniteFindManyDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindManyArgs, TQueryFnData = Array<Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findMany`, args, options, fetch);
}

export function useSuspenseFindManyDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindManyArgs, TQueryFnData = Array<Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindManyArgs, TQueryFnData = Array<Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findMany`, args, options, fetch);
}

export function useFindUniqueDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindUniqueArgs, TQueryFnData = Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindUniqueArgs, TQueryFnData = Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findUnique`, args, options, fetch);
}

export function useFindFirstDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindFirstArgs, TQueryFnData = Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsFindFirstArgs, TQueryFnData = Prisma.DataroomViewerGroupAccessControlsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/findFirst`, args, options, fetch);
}

export function useUpdateDataroomViewerGroupAccessControls(options?: Omit<(UseMutationOptions<(DataroomViewerGroupAccessControls | undefined), DefaultError, Prisma.DataroomViewerGroupAccessControlsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataroomViewerGroupAccessControlsUpdateArgs, DefaultError, DataroomViewerGroupAccessControls, true>('DataroomViewerGroupAccessControls', 'PUT', `${endpoint}/dataroomViewerGroupAccessControls/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataroomViewerGroupAccessControlsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyDataroomViewerGroupAccessControls(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DataroomViewerGroupAccessControlsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataroomViewerGroupAccessControlsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('DataroomViewerGroupAccessControls', 'PUT', `${endpoint}/dataroomViewerGroupAccessControls/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataroomViewerGroupAccessControlsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertDataroomViewerGroupAccessControls(options?: Omit<(UseMutationOptions<(DataroomViewerGroupAccessControls | undefined), DefaultError, Prisma.DataroomViewerGroupAccessControlsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataroomViewerGroupAccessControlsUpsertArgs, DefaultError, DataroomViewerGroupAccessControls, true>('DataroomViewerGroupAccessControls', 'POST', `${endpoint}/dataroomViewerGroupAccessControls/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataroomViewerGroupAccessControlsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteDataroomViewerGroupAccessControls(options?: Omit<(UseMutationOptions<(DataroomViewerGroupAccessControls | undefined), DefaultError, Prisma.DataroomViewerGroupAccessControlsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataroomViewerGroupAccessControlsDeleteArgs, DefaultError, DataroomViewerGroupAccessControls, true>('DataroomViewerGroupAccessControls', 'DELETE', `${endpoint}/dataroomViewerGroupAccessControls/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataroomViewerGroupAccessControlsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DataroomViewerGroupAccessControls, Prisma.DataroomViewerGroupAccessControlsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyDataroomViewerGroupAccessControls(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DataroomViewerGroupAccessControlsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DataroomViewerGroupAccessControlsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('DataroomViewerGroupAccessControls', 'DELETE', `${endpoint}/dataroomViewerGroupAccessControls/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DataroomViewerGroupAccessControlsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DataroomViewerGroupAccessControlsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsAggregateArgs, TQueryFnData = Prisma.GetDataroomViewerGroupAccessControlsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsAggregateArgs, TQueryFnData = Prisma.GetDataroomViewerGroupAccessControlsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/aggregate`, args, options, fetch);
}

export function useGroupByDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.DataroomViewerGroupAccessControlsGroupByArgs['orderBy'] } : { orderBy?: Prisma.DataroomViewerGroupAccessControlsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.DataroomViewerGroupAccessControlsGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.DataroomViewerGroupAccessControlsGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.DataroomViewerGroupAccessControlsGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.DataroomViewerGroupAccessControlsGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DataroomViewerGroupAccessControlsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.DataroomViewerGroupAccessControlsGroupByArgs['orderBy'] } : { orderBy?: Prisma.DataroomViewerGroupAccessControlsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.DataroomViewerGroupAccessControlsGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.DataroomViewerGroupAccessControlsGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.DataroomViewerGroupAccessControlsGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.DataroomViewerGroupAccessControlsGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DataroomViewerGroupAccessControlsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/groupBy`, args, options, fetch);
}

export function useCountDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.DataroomViewerGroupAccessControlsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/count`, args, options, fetch);
}

export function useSuspenseCountDataroomViewerGroupAccessControls<TArgs extends Prisma.DataroomViewerGroupAccessControlsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.DataroomViewerGroupAccessControlsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.DataroomViewerGroupAccessControlsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/count`, args, options, fetch);
}

export function useCheckDataroomViewerGroupAccessControls<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { createdBy?: string; updatedBy?: string; tenantId?: string; id?: string; groupId?: string; itemId?: string; itemType?: string; canView?: boolean; canDownload?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('DataroomViewerGroupAccessControls', `${endpoint}/dataroomViewerGroupAccessControls/check`, args, options, fetch);
}
