/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import type { Document, Prisma } from '../../../../node_modules/.prisma/client';
import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateDocument(options?: Omit<UseMutationOptions<Document | undefined, DefaultError, Prisma.DocumentCreateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.DocumentCreateArgs, DefaultError, Document, true>('Document', 'POST', `${endpoint}/document/create`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.DocumentCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.DocumentCreateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.DocumentCreateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyDocument(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DocumentCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.DocumentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Document', 'POST', `${endpoint}/document/createMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.DocumentCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.DocumentCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DocumentCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyDocument<
  TArgs extends Prisma.DocumentFindManyArgs,
  TQueryFnData = Array<Prisma.DocumentGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.DocumentFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findMany`, args, options, fetch);
}

export function useInfiniteFindManyDocument<TArgs extends Prisma.DocumentFindManyArgs, TQueryFnData = Array<Prisma.DocumentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.DocumentFindManyArgs>,
  options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findMany`, args, options, fetch);
}

export function useSuspenseFindManyDocument<
  TArgs extends Prisma.DocumentFindManyArgs,
  TQueryFnData = Array<Prisma.DocumentGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.DocumentFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyDocument<TArgs extends Prisma.DocumentFindManyArgs, TQueryFnData = Array<Prisma.DocumentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.DocumentFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findMany`, args, options, fetch);
}

export function useFindUniqueDocument<
  TArgs extends Prisma.DocumentFindUniqueArgs,
  TQueryFnData = Prisma.DocumentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.DocumentFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueDocument<
  TArgs extends Prisma.DocumentFindUniqueArgs,
  TQueryFnData = Prisma.DocumentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.DocumentFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findUnique`, args, options, fetch);
}

export function useFindFirstDocument<
  TArgs extends Prisma.DocumentFindFirstArgs,
  TQueryFnData = Prisma.DocumentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.DocumentFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstDocument<
  TArgs extends Prisma.DocumentFindFirstArgs,
  TQueryFnData = Prisma.DocumentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.DocumentFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/findFirst`, args, options, fetch);
}

export function useUpdateDocument(options?: Omit<UseMutationOptions<Document | undefined, DefaultError, Prisma.DocumentUpdateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.DocumentUpdateArgs, DefaultError, Document, true>('Document', 'PUT', `${endpoint}/document/update`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.DocumentUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.DocumentUpdateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.DocumentUpdateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyDocument(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DocumentUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.DocumentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Document', 'PUT', `${endpoint}/document/updateMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.DocumentUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.DocumentUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DocumentUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertDocument(options?: Omit<UseMutationOptions<Document | undefined, DefaultError, Prisma.DocumentUpsertArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.DocumentUpsertArgs, DefaultError, Document, true>('Document', 'POST', `${endpoint}/document/upsert`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.DocumentUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.DocumentUpsertArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.DocumentUpsertArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteDocument(options?: Omit<UseMutationOptions<Document | undefined, DefaultError, Prisma.DocumentDeleteArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.DocumentDeleteArgs, DefaultError, Document, true>('Document', 'DELETE', `${endpoint}/document/delete`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.DocumentDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.DocumentDeleteArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.DocumentDeleteArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Document, Prisma.DocumentGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyDocument(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DocumentDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.DocumentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Document', 'DELETE', `${endpoint}/document/deleteMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.DocumentDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.DocumentDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DocumentDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateDocument<TArgs extends Prisma.DocumentAggregateArgs, TQueryFnData = Prisma.GetDocumentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.DocumentAggregateArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateDocument<TArgs extends Prisma.DocumentAggregateArgs, TQueryFnData = Prisma.GetDocumentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.DocumentAggregateArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/aggregate`, args, options, fetch);
}

export function useGroupByDocument<
  TArgs extends Prisma.DocumentGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.DocumentGroupByArgs['orderBy'] } : { orderBy?: Prisma.DocumentGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.DocumentGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.DocumentGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.DocumentGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.DocumentGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DocumentGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByDocument<
  TArgs extends Prisma.DocumentGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.DocumentGroupByArgs['orderBy'] } : { orderBy?: Prisma.DocumentGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.DocumentGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.DocumentGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.DocumentGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.DocumentGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DocumentGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/groupBy`, args, options, fetch);
}

export function useCountDocument<
  TArgs extends Prisma.DocumentCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.DocumentCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.DocumentCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/count`, args, options, fetch);
}

export function useSuspenseCountDocument<
  TArgs extends Prisma.DocumentCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.DocumentCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.DocumentCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Document', `${endpoint}/document/count`, args, options, fetch);
}

export function useCheckDocument<TError = DefaultError>(
  args: {
    operation: PolicyCrudKind;
    where?: {
      createdBy?: string;
      updatedBy?: string;
      tenantId?: string;
      id?: string;
      name?: string;
      description?: string;
      file?: string;
      originalFile?: string;
      type?: string;
      contentType?: string;
      storageType?: string;
      numPages?: number;
      status?: string;
      assistantEnabled?: boolean;
      advancedExcelEnabled?: boolean;
      downloadOnly?: boolean;
      ownerId?: string;
      folderId?: string;
      dataroomId?: string;
      orderIndex?: number;
      requirementComplianceTrackingId?: string;
    };
  },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('Document', `${endpoint}/document/check`, args, options, fetch);
}
