/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';
import type { ExecutionModelInstance, Prisma } from '.prisma/client';

type DefaultError = QueryError;

export function useCreateExecutionModelInstance(
  options?: Omit<UseMutationOptions<ExecutionModelInstance | undefined, DefaultError, Prisma.ExecutionModelInstanceCreateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ExecutionModelInstanceCreateArgs, DefaultError, ExecutionModelInstance, true>(
    'ExecutionModelInstance',
    'POST',
    `${endpoint}/executionModelInstance/create`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ExecutionModelInstanceCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceCreateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceCreateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyExecutionModelInstance(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ExecutionModelInstanceCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ExecutionModelInstanceCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'ExecutionModelInstance',
    'POST',
    `${endpoint}/executionModelInstance/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ExecutionModelInstanceCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindManyArgs,
  TQueryFnData = Array<Prisma.ExecutionModelInstanceGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findMany`, args, options, fetch);
}

export function useInfiniteFindManyExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindManyArgs,
  TQueryFnData = Array<Prisma.ExecutionModelInstanceGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findMany`, args, options, fetch);
}

export function useSuspenseFindManyExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindManyArgs,
  TQueryFnData = Array<Prisma.ExecutionModelInstanceGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindManyArgs,
  TQueryFnData = Array<Prisma.ExecutionModelInstanceGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findMany`, args, options, fetch);
}

export function useFindUniqueExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindUniqueArgs,
  TQueryFnData = Prisma.ExecutionModelInstanceGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindUniqueArgs,
  TQueryFnData = Prisma.ExecutionModelInstanceGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findUnique`, args, options, fetch);
}

export function useFindFirstExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindFirstArgs,
  TQueryFnData = Prisma.ExecutionModelInstanceGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceFindFirstArgs,
  TQueryFnData = Prisma.ExecutionModelInstanceGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/findFirst`, args, options, fetch);
}

export function useUpdateExecutionModelInstance(
  options?: Omit<UseMutationOptions<ExecutionModelInstance | undefined, DefaultError, Prisma.ExecutionModelInstanceUpdateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ExecutionModelInstanceUpdateArgs, DefaultError, ExecutionModelInstance, true>(
    'ExecutionModelInstance',
    'PUT',
    `${endpoint}/executionModelInstance/update`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ExecutionModelInstanceUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceUpdateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceUpdateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyExecutionModelInstance(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ExecutionModelInstanceUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ExecutionModelInstanceUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'ExecutionModelInstance',
    'PUT',
    `${endpoint}/executionModelInstance/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ExecutionModelInstanceUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertExecutionModelInstance(
  options?: Omit<UseMutationOptions<ExecutionModelInstance | undefined, DefaultError, Prisma.ExecutionModelInstanceUpsertArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ExecutionModelInstanceUpsertArgs, DefaultError, ExecutionModelInstance, true>(
    'ExecutionModelInstance',
    'POST',
    `${endpoint}/executionModelInstance/upsert`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ExecutionModelInstanceUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceUpsertArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceUpsertArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteExecutionModelInstance(
  options?: Omit<UseMutationOptions<ExecutionModelInstance | undefined, DefaultError, Prisma.ExecutionModelInstanceDeleteArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ExecutionModelInstanceDeleteArgs, DefaultError, ExecutionModelInstance, true>(
    'ExecutionModelInstance',
    'DELETE',
    `${endpoint}/executionModelInstance/delete`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ExecutionModelInstanceDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceDeleteArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceDeleteArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, ExecutionModelInstance, Prisma.ExecutionModelInstanceGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyExecutionModelInstance(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ExecutionModelInstanceDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ExecutionModelInstanceDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'ExecutionModelInstance',
    'DELETE',
    `${endpoint}/executionModelInstance/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ExecutionModelInstanceDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ExecutionModelInstanceDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceAggregateArgs,
  TQueryFnData = Prisma.GetExecutionModelInstanceAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceAggregateArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceAggregateArgs,
  TQueryFnData = Prisma.GetExecutionModelInstanceAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceAggregateArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/aggregate`, args, options, fetch);
}

export function useGroupByExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ExecutionModelInstanceGroupByArgs['orderBy'] } : { orderBy?: Prisma.ExecutionModelInstanceGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.ExecutionModelInstanceGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.ExecutionModelInstanceGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.ExecutionModelInstanceGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.ExecutionModelInstanceGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ExecutionModelInstanceGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ExecutionModelInstanceGroupByArgs['orderBy'] } : { orderBy?: Prisma.ExecutionModelInstanceGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.ExecutionModelInstanceGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.ExecutionModelInstanceGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.ExecutionModelInstanceGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.ExecutionModelInstanceGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ExecutionModelInstanceGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/groupBy`, args, options, fetch);
}

export function useCountExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ExecutionModelInstanceCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/count`, args, options, fetch);
}

export function useSuspenseCountExecutionModelInstance<
  TArgs extends Prisma.ExecutionModelInstanceCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ExecutionModelInstanceCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ExecutionModelInstanceCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/count`, args, options, fetch);
}

export function useCheckExecutionModelInstance<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { createdBy?: string; updatedBy?: string; tenantId?: string; id?: string; flowId?: string; referenceId?: string; status?: string } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('ExecutionModelInstance', `${endpoint}/executionModelInstance/check`, args, options, fetch);
}
