/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { LinkEmailVerificationCode, Prisma } from '@zenstackhq/runtime/models';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateLinkEmailVerificationCode(
  options?: Omit<UseMutationOptions<LinkEmailVerificationCode | undefined, DefaultError, Prisma.LinkEmailVerificationCodeCreateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.LinkEmailVerificationCodeCreateArgs, DefaultError, LinkEmailVerificationCode, true>(
    'LinkEmailVerificationCode',
    'POST',
    `${endpoint}/linkEmailVerificationCode/create`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.LinkEmailVerificationCodeCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeCreateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeCreateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyLinkEmailVerificationCode(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LinkEmailVerificationCodeCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.LinkEmailVerificationCodeCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'LinkEmailVerificationCode',
    'POST',
    `${endpoint}/linkEmailVerificationCode/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.LinkEmailVerificationCodeCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindManyArgs,
  TQueryFnData = Array<Prisma.LinkEmailVerificationCodeGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findMany`, args, options, fetch);
}

export function useInfiniteFindManyLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindManyArgs,
  TQueryFnData = Array<Prisma.LinkEmailVerificationCodeGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindManyArgs>,
  options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findMany`, args, options, fetch);
}

export function useSuspenseFindManyLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindManyArgs,
  TQueryFnData = Array<Prisma.LinkEmailVerificationCodeGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindManyArgs,
  TQueryFnData = Array<Prisma.LinkEmailVerificationCodeGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findMany`, args, options, fetch);
}

export function useFindUniqueLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindUniqueArgs,
  TQueryFnData = Prisma.LinkEmailVerificationCodeGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindUniqueArgs,
  TQueryFnData = Prisma.LinkEmailVerificationCodeGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findUnique`, args, options, fetch);
}

export function useFindFirstLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindFirstArgs,
  TQueryFnData = Prisma.LinkEmailVerificationCodeGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeFindFirstArgs,
  TQueryFnData = Prisma.LinkEmailVerificationCodeGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/findFirst`, args, options, fetch);
}

export function useUpdateLinkEmailVerificationCode(
  options?: Omit<UseMutationOptions<LinkEmailVerificationCode | undefined, DefaultError, Prisma.LinkEmailVerificationCodeUpdateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.LinkEmailVerificationCodeUpdateArgs, DefaultError, LinkEmailVerificationCode, true>(
    'LinkEmailVerificationCode',
    'PUT',
    `${endpoint}/linkEmailVerificationCode/update`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.LinkEmailVerificationCodeUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeUpdateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeUpdateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyLinkEmailVerificationCode(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LinkEmailVerificationCodeUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.LinkEmailVerificationCodeUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'LinkEmailVerificationCode',
    'PUT',
    `${endpoint}/linkEmailVerificationCode/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.LinkEmailVerificationCodeUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertLinkEmailVerificationCode(
  options?: Omit<UseMutationOptions<LinkEmailVerificationCode | undefined, DefaultError, Prisma.LinkEmailVerificationCodeUpsertArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.LinkEmailVerificationCodeUpsertArgs, DefaultError, LinkEmailVerificationCode, true>(
    'LinkEmailVerificationCode',
    'POST',
    `${endpoint}/linkEmailVerificationCode/upsert`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.LinkEmailVerificationCodeUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeUpsertArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeUpsertArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteLinkEmailVerificationCode(
  options?: Omit<UseMutationOptions<LinkEmailVerificationCode | undefined, DefaultError, Prisma.LinkEmailVerificationCodeDeleteArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.LinkEmailVerificationCodeDeleteArgs, DefaultError, LinkEmailVerificationCode, true>(
    'LinkEmailVerificationCode',
    'DELETE',
    `${endpoint}/linkEmailVerificationCode/delete`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.LinkEmailVerificationCodeDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeDeleteArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeDeleteArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, LinkEmailVerificationCode, Prisma.LinkEmailVerificationCodeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyLinkEmailVerificationCode(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LinkEmailVerificationCodeDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.LinkEmailVerificationCodeDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'LinkEmailVerificationCode',
    'DELETE',
    `${endpoint}/linkEmailVerificationCode/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.LinkEmailVerificationCodeDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LinkEmailVerificationCodeDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeAggregateArgs,
  TQueryFnData = Prisma.GetLinkEmailVerificationCodeAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeAggregateArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeAggregateArgs,
  TQueryFnData = Prisma.GetLinkEmailVerificationCodeAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeAggregateArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/aggregate`, args, options, fetch);
}

export function useGroupByLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LinkEmailVerificationCodeGroupByArgs['orderBy'] } : { orderBy?: Prisma.LinkEmailVerificationCodeGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.LinkEmailVerificationCodeGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.LinkEmailVerificationCodeGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.LinkEmailVerificationCodeGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.LinkEmailVerificationCodeGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LinkEmailVerificationCodeGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LinkEmailVerificationCodeGroupByArgs['orderBy'] } : { orderBy?: Prisma.LinkEmailVerificationCodeGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.LinkEmailVerificationCodeGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.LinkEmailVerificationCodeGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.LinkEmailVerificationCodeGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.LinkEmailVerificationCodeGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LinkEmailVerificationCodeGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/groupBy`, args, options, fetch);
}

export function useCountLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LinkEmailVerificationCodeCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/count`, args, options, fetch);
}

export function useSuspenseCountLinkEmailVerificationCode<
  TArgs extends Prisma.LinkEmailVerificationCodeCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LinkEmailVerificationCodeCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.LinkEmailVerificationCodeCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/count`, args, options, fetch);
}

export function useCheckLinkEmailVerificationCode<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { createdBy?: string; updatedBy?: string; tenantId?: string; id?: string; email?: string; code?: string; linkId?: string; verified?: boolean } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('LinkEmailVerificationCode', `${endpoint}/linkEmailVerificationCode/check`, args, options, fetch);
}
