/******************************************************************************
 * This file was generated by ZenStack CLI 2.9.2.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, PasswordResetToken } from '@zenstackhq/runtime/models';
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreatePasswordResetToken(
  options?: Omit<UseMutationOptions<PasswordResetToken | undefined, DefaultError, Prisma.PasswordResetTokenCreateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PasswordResetTokenCreateArgs, DefaultError, PasswordResetToken, true>(
    'PasswordResetToken',
    'POST',
    `${endpoint}/passwordResetToken/create`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PasswordResetTokenCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.PasswordResetTokenCreateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.PasswordResetTokenCreateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyPasswordResetToken(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PasswordResetTokenCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PasswordResetTokenCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'PasswordResetToken',
    'POST',
    `${endpoint}/passwordResetToken/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PasswordResetTokenCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.PasswordResetTokenCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PasswordResetTokenCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindManyArgs,
  TQueryFnData = Array<Prisma.PasswordResetTokenGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findMany`, args, options, fetch);
}

export function useInfiniteFindManyPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindManyArgs,
  TQueryFnData = Array<Prisma.PasswordResetTokenGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindManyArgs>,
  options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findMany`, args, options, fetch);
}

export function useSuspenseFindManyPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindManyArgs,
  TQueryFnData = Array<Prisma.PasswordResetTokenGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindManyArgs,
  TQueryFnData = Array<Prisma.PasswordResetTokenGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findMany`, args, options, fetch);
}

export function useFindUniquePasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindUniqueArgs,
  TQueryFnData = Prisma.PasswordResetTokenGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquePasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindUniqueArgs,
  TQueryFnData = Prisma.PasswordResetTokenGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findUnique`, args, options, fetch);
}

export function useFindFirstPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindFirstArgs,
  TQueryFnData = Prisma.PasswordResetTokenGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenFindFirstArgs,
  TQueryFnData = Prisma.PasswordResetTokenGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/findFirst`, args, options, fetch);
}

export function useUpdatePasswordResetToken(
  options?: Omit<UseMutationOptions<PasswordResetToken | undefined, DefaultError, Prisma.PasswordResetTokenUpdateArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PasswordResetTokenUpdateArgs, DefaultError, PasswordResetToken, true>(
    'PasswordResetToken',
    'PUT',
    `${endpoint}/passwordResetToken/update`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PasswordResetTokenUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.PasswordResetTokenUpdateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.PasswordResetTokenUpdateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyPasswordResetToken(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PasswordResetTokenUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PasswordResetTokenUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'PasswordResetToken',
    'PUT',
    `${endpoint}/passwordResetToken/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PasswordResetTokenUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.PasswordResetTokenUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PasswordResetTokenUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertPasswordResetToken(
  options?: Omit<UseMutationOptions<PasswordResetToken | undefined, DefaultError, Prisma.PasswordResetTokenUpsertArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PasswordResetTokenUpsertArgs, DefaultError, PasswordResetToken, true>(
    'PasswordResetToken',
    'POST',
    `${endpoint}/passwordResetToken/upsert`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PasswordResetTokenUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.PasswordResetTokenUpsertArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.PasswordResetTokenUpsertArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeletePasswordResetToken(
  options?: Omit<UseMutationOptions<PasswordResetToken | undefined, DefaultError, Prisma.PasswordResetTokenDeleteArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PasswordResetTokenDeleteArgs, DefaultError, PasswordResetToken, true>(
    'PasswordResetToken',
    'DELETE',
    `${endpoint}/passwordResetToken/delete`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PasswordResetTokenDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.PasswordResetTokenDeleteArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.PasswordResetTokenDeleteArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PasswordResetToken, Prisma.PasswordResetTokenGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyPasswordResetToken(
  options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PasswordResetTokenDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PasswordResetTokenDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'PasswordResetToken',
    'DELETE',
    `${endpoint}/passwordResetToken/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PasswordResetTokenDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.PasswordResetTokenDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PasswordResetTokenDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregatePasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenAggregateArgs,
  TQueryFnData = Prisma.GetPasswordResetTokenAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenAggregateArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/aggregate`, args, options, fetch);
}

export function useSuspenseAggregatePasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenAggregateArgs,
  TQueryFnData = Prisma.GetPasswordResetTokenAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenAggregateArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/aggregate`, args, options, fetch);
}

export function useGroupByPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.PasswordResetTokenGroupByArgs['orderBy'] }
    : { orderBy?: Prisma.PasswordResetTokenGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.PasswordResetTokenGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.PasswordResetTokenGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.PasswordResetTokenGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.PasswordResetTokenGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PasswordResetTokenGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.PasswordResetTokenGroupByArgs['orderBy'] }
    : { orderBy?: Prisma.PasswordResetTokenGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.PasswordResetTokenGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.PasswordResetTokenGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.PasswordResetTokenGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.PasswordResetTokenGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PasswordResetTokenGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/groupBy`, args, options, fetch);
}

export function useCountPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenCountArgs,
  TQueryFnData = TArgs extends { select: any }
    ? TArgs['select'] extends true
      ? number
      : Prisma.GetScalarType<TArgs['select'], Prisma.PasswordResetTokenCountAggregateOutputType>
    : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/count`, args, options, fetch);
}

export function useSuspenseCountPasswordResetToken<
  TArgs extends Prisma.PasswordResetTokenCountArgs,
  TQueryFnData = TArgs extends { select: any }
    ? TArgs['select'] extends true
      ? number
      : Prisma.GetScalarType<TArgs['select'], Prisma.PasswordResetTokenCountAggregateOutputType>
    : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PasswordResetTokenCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/count`, args, options, fetch);
}

export function useCheckPasswordResetToken<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { id?: string; email?: string; token?: string } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('PasswordResetToken', `${endpoint}/passwordResetToken/check`, args, options, fetch);
}
