/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { PlanLimits, Prisma } from '@zenstackhq/runtime/models';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreatePlanLimits(options?: Omit<UseMutationOptions<PlanLimits | undefined, DefaultError, Prisma.PlanLimitsCreateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PlanLimitsCreateArgs, DefaultError, PlanLimits, true>('PlanLimits', 'POST', `${endpoint}/planLimits/create`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PlanLimitsCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.PlanLimitsCreateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.PlanLimitsCreateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyPlanLimits(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PlanLimitsCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PlanLimitsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'PlanLimits',
    'POST',
    `${endpoint}/planLimits/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PlanLimitsCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.PlanLimitsCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PlanLimitsCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyPlanLimits<
  TArgs extends Prisma.PlanLimitsFindManyArgs,
  TQueryFnData = Array<Prisma.PlanLimitsGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findMany`, args, options, fetch);
}

export function useInfiniteFindManyPlanLimits<TArgs extends Prisma.PlanLimitsFindManyArgs, TQueryFnData = Array<Prisma.PlanLimitsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindManyArgs>,
  options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findMany`, args, options, fetch);
}

export function useSuspenseFindManyPlanLimits<
  TArgs extends Prisma.PlanLimitsFindManyArgs,
  TQueryFnData = Array<Prisma.PlanLimitsGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyPlanLimits<
  TArgs extends Prisma.PlanLimitsFindManyArgs,
  TQueryFnData = Array<Prisma.PlanLimitsGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findMany`, args, options, fetch);
}

export function useFindUniquePlanLimits<
  TArgs extends Prisma.PlanLimitsFindUniqueArgs,
  TQueryFnData = Prisma.PlanLimitsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquePlanLimits<
  TArgs extends Prisma.PlanLimitsFindUniqueArgs,
  TQueryFnData = Prisma.PlanLimitsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findUnique`, args, options, fetch);
}

export function useFindFirstPlanLimits<
  TArgs extends Prisma.PlanLimitsFindFirstArgs,
  TQueryFnData = Prisma.PlanLimitsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstPlanLimits<
  TArgs extends Prisma.PlanLimitsFindFirstArgs,
  TQueryFnData = Prisma.PlanLimitsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/findFirst`, args, options, fetch);
}

export function useUpdatePlanLimits(options?: Omit<UseMutationOptions<PlanLimits | undefined, DefaultError, Prisma.PlanLimitsUpdateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PlanLimitsUpdateArgs, DefaultError, PlanLimits, true>('PlanLimits', 'PUT', `${endpoint}/planLimits/update`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PlanLimitsUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.PlanLimitsUpdateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.PlanLimitsUpdateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyPlanLimits(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PlanLimitsUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PlanLimitsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'PlanLimits',
    'PUT',
    `${endpoint}/planLimits/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PlanLimitsUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.PlanLimitsUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PlanLimitsUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertPlanLimits(options?: Omit<UseMutationOptions<PlanLimits | undefined, DefaultError, Prisma.PlanLimitsUpsertArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PlanLimitsUpsertArgs, DefaultError, PlanLimits, true>('PlanLimits', 'POST', `${endpoint}/planLimits/upsert`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PlanLimitsUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.PlanLimitsUpsertArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.PlanLimitsUpsertArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeletePlanLimits(options?: Omit<UseMutationOptions<PlanLimits | undefined, DefaultError, Prisma.PlanLimitsDeleteArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PlanLimitsDeleteArgs, DefaultError, PlanLimits, true>('PlanLimits', 'DELETE', `${endpoint}/planLimits/delete`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PlanLimitsDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.PlanLimitsDeleteArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.PlanLimitsDeleteArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, PlanLimits, Prisma.PlanLimitsGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyPlanLimits(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PlanLimitsDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.PlanLimitsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'PlanLimits',
    'DELETE',
    `${endpoint}/planLimits/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.PlanLimitsDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.PlanLimitsDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PlanLimitsDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregatePlanLimits<TArgs extends Prisma.PlanLimitsAggregateArgs, TQueryFnData = Prisma.GetPlanLimitsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsAggregateArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/aggregate`, args, options, fetch);
}

export function useSuspenseAggregatePlanLimits<TArgs extends Prisma.PlanLimitsAggregateArgs, TQueryFnData = Prisma.GetPlanLimitsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsAggregateArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/aggregate`, args, options, fetch);
}

export function useGroupByPlanLimits<
  TArgs extends Prisma.PlanLimitsGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PlanLimitsGroupByArgs['orderBy'] } : { orderBy?: Prisma.PlanLimitsGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.PlanLimitsGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.PlanLimitsGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.PlanLimitsGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.PlanLimitsGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PlanLimitsGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByPlanLimits<
  TArgs extends Prisma.PlanLimitsGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PlanLimitsGroupByArgs['orderBy'] } : { orderBy?: Prisma.PlanLimitsGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.PlanLimitsGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.PlanLimitsGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.PlanLimitsGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.PlanLimitsGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PlanLimitsGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/groupBy`, args, options, fetch);
}

export function useCountPlanLimits<
  TArgs extends Prisma.PlanLimitsCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PlanLimitsCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/count`, args, options, fetch);
}

export function useSuspenseCountPlanLimits<
  TArgs extends Prisma.PlanLimitsCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PlanLimitsCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.PlanLimitsCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('PlanLimits', `${endpoint}/planLimits/count`, args, options, fetch);
}

export function useCheckPlanLimits<TError = DefaultError>(
  args: {
    operation: PolicyCrudKind;
    where?: {
      createdBy?: string;
      updatedBy?: string;
      tenantId?: string;
      id?: string;
      datarooms?: number;
      users?: number;
      domains?: number;
      customDomainOnPro?: boolean;
      customDomainInDataroom?: boolean;
      enableExcelAdvancedMode?: boolean;
      replicateDataroomFolders?: boolean;
      ignoredDomains?: string;
      globalBlockList?: string;
      plan?: string;
      stripeId?: string;
      subscriptionId?: string;
      limits?: string;
    };
  },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('PlanLimits', `${endpoint}/planLimits/check`, args, options, fetch);
}
