/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, RequestHierarchyLevel } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateRequestHierarchyLevel(options?: Omit<(UseMutationOptions<(RequestHierarchyLevel | undefined), DefaultError, Prisma.RequestHierarchyLevelCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyLevelCreateArgs, DefaultError, RequestHierarchyLevel, true>('RequestHierarchyLevel', 'POST', `${endpoint}/requestHierarchyLevel/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyLevelCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyRequestHierarchyLevel(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestHierarchyLevelCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyLevelCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('RequestHierarchyLevel', 'POST', `${endpoint}/requestHierarchyLevel/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyLevelCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findMany`, args, options, fetch);
}

export function useInfiniteFindManyRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyLevelGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findMany`, args, options, fetch);
}

export function useSuspenseFindManyRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyLevelGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findMany`, args, options, fetch);
}

export function useFindUniqueRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindUniqueArgs, TQueryFnData = Prisma.RequestHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindUniqueArgs, TQueryFnData = Prisma.RequestHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findUnique`, args, options, fetch);
}

export function useFindFirstRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindFirstArgs, TQueryFnData = Prisma.RequestHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelFindFirstArgs, TQueryFnData = Prisma.RequestHierarchyLevelGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/findFirst`, args, options, fetch);
}

export function useUpdateRequestHierarchyLevel(options?: Omit<(UseMutationOptions<(RequestHierarchyLevel | undefined), DefaultError, Prisma.RequestHierarchyLevelUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyLevelUpdateArgs, DefaultError, RequestHierarchyLevel, true>('RequestHierarchyLevel', 'PUT', `${endpoint}/requestHierarchyLevel/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyLevelUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyRequestHierarchyLevel(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestHierarchyLevelUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyLevelUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('RequestHierarchyLevel', 'PUT', `${endpoint}/requestHierarchyLevel/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyLevelUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertRequestHierarchyLevel(options?: Omit<(UseMutationOptions<(RequestHierarchyLevel | undefined), DefaultError, Prisma.RequestHierarchyLevelUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyLevelUpsertArgs, DefaultError, RequestHierarchyLevel, true>('RequestHierarchyLevel', 'POST', `${endpoint}/requestHierarchyLevel/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyLevelUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteRequestHierarchyLevel(options?: Omit<(UseMutationOptions<(RequestHierarchyLevel | undefined), DefaultError, Prisma.RequestHierarchyLevelDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyLevelDeleteArgs, DefaultError, RequestHierarchyLevel, true>('RequestHierarchyLevel', 'DELETE', `${endpoint}/requestHierarchyLevel/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyLevelDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchyLevel, Prisma.RequestHierarchyLevelGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyRequestHierarchyLevel(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestHierarchyLevelDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyLevelDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('RequestHierarchyLevel', 'DELETE', `${endpoint}/requestHierarchyLevel/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyLevelDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyLevelDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelAggregateArgs, TQueryFnData = Prisma.GetRequestHierarchyLevelAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelAggregateArgs, TQueryFnData = Prisma.GetRequestHierarchyLevelAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/aggregate`, args, options, fetch);
}

export function useGroupByRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.RequestHierarchyLevelGroupByArgs['orderBy'] } : { orderBy?: Prisma.RequestHierarchyLevelGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.RequestHierarchyLevelGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.RequestHierarchyLevelGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyLevelGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyLevelGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.RequestHierarchyLevelGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.RequestHierarchyLevelGroupByArgs['orderBy'] } : { orderBy?: Prisma.RequestHierarchyLevelGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.RequestHierarchyLevelGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.RequestHierarchyLevelGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyLevelGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyLevelGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.RequestHierarchyLevelGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/groupBy`, args, options, fetch);
}

export function useCountRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.RequestHierarchyLevelCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/count`, args, options, fetch);
}

export function useSuspenseCountRequestHierarchyLevel<TArgs extends Prisma.RequestHierarchyLevelCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.RequestHierarchyLevelCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyLevelCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/count`, args, options, fetch);
}

export function useCheckRequestHierarchyLevel<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; description?: string; isActive?: boolean; createdBy?: string; updatedBy?: string; tenantId?: string; hierarchyId?: string; position?: number }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('RequestHierarchyLevel', `${endpoint}/requestHierarchyLevel/check`, args, options, fetch);
}
