/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { Prisma, RequestDataroom } from '@zenstackhq/runtime/models';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateRequestDataroom(options?: Omit<UseMutationOptions<RequestDataroom | undefined, DefaultError, Prisma.RequestDataroomCreateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.RequestDataroomCreateArgs, DefaultError, RequestDataroom, true>(
    'RequestDataroom',
    'POST',
    `${endpoint}/requestDataroom/create`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.RequestDataroomCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.RequestDataroomCreateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.RequestDataroomCreateArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyRequestDataroom(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestDataroomCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.RequestDataroomCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'RequestDataroom',
    'POST',
    `${endpoint}/requestDataroom/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.RequestDataroomCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.RequestDataroomCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestDataroomCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindManyArgs,
  TQueryFnData = Array<Prisma.RequestDataroomGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findMany`, args, options, fetch);
}

export function useInfiniteFindManyRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindManyArgs,
  TQueryFnData = Array<Prisma.RequestDataroomGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findMany`, args, options, fetch);
}

export function useSuspenseFindManyRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindManyArgs,
  TQueryFnData = Array<Prisma.RequestDataroomGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindManyArgs,
  TQueryFnData = Array<Prisma.RequestDataroomGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findMany`, args, options, fetch);
}

export function useFindUniqueRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindUniqueArgs,
  TQueryFnData = Prisma.RequestDataroomGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindUniqueArgs,
  TQueryFnData = Prisma.RequestDataroomGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findUnique`, args, options, fetch);
}

export function useFindFirstRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindFirstArgs,
  TQueryFnData = Prisma.RequestDataroomGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstRequestDataroom<
  TArgs extends Prisma.RequestDataroomFindFirstArgs,
  TQueryFnData = Prisma.RequestDataroomGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/findFirst`, args, options, fetch);
}

export function useUpdateRequestDataroom(options?: Omit<UseMutationOptions<RequestDataroom | undefined, DefaultError, Prisma.RequestDataroomUpdateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.RequestDataroomUpdateArgs, DefaultError, RequestDataroom, true>(
    'RequestDataroom',
    'PUT',
    `${endpoint}/requestDataroom/update`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.RequestDataroomUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.RequestDataroomUpdateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.RequestDataroomUpdateArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyRequestDataroom(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestDataroomUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.RequestDataroomUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'RequestDataroom',
    'PUT',
    `${endpoint}/requestDataroom/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.RequestDataroomUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.RequestDataroomUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestDataroomUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertRequestDataroom(options?: Omit<UseMutationOptions<RequestDataroom | undefined, DefaultError, Prisma.RequestDataroomUpsertArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.RequestDataroomUpsertArgs, DefaultError, RequestDataroom, true>(
    'RequestDataroom',
    'POST',
    `${endpoint}/requestDataroom/upsert`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.RequestDataroomUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.RequestDataroomUpsertArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.RequestDataroomUpsertArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteRequestDataroom(options?: Omit<UseMutationOptions<RequestDataroom | undefined, DefaultError, Prisma.RequestDataroomDeleteArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.RequestDataroomDeleteArgs, DefaultError, RequestDataroom, true>(
    'RequestDataroom',
    'DELETE',
    `${endpoint}/requestDataroom/delete`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.RequestDataroomDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.RequestDataroomDeleteArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.RequestDataroomDeleteArgs>> &
          ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, RequestDataroom, Prisma.RequestDataroomGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyRequestDataroom(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestDataroomDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.RequestDataroomDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'RequestDataroom',
    'DELETE',
    `${endpoint}/requestDataroom/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.RequestDataroomDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.RequestDataroomDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestDataroomDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateRequestDataroom<
  TArgs extends Prisma.RequestDataroomAggregateArgs,
  TQueryFnData = Prisma.GetRequestDataroomAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomAggregateArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateRequestDataroom<
  TArgs extends Prisma.RequestDataroomAggregateArgs,
  TQueryFnData = Prisma.GetRequestDataroomAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomAggregateArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/aggregate`, args, options, fetch);
}

export function useGroupByRequestDataroom<
  TArgs extends Prisma.RequestDataroomGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.RequestDataroomGroupByArgs['orderBy'] } : { orderBy?: Prisma.RequestDataroomGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.RequestDataroomGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.RequestDataroomGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.RequestDataroomGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.RequestDataroomGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.RequestDataroomGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByRequestDataroom<
  TArgs extends Prisma.RequestDataroomGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.RequestDataroomGroupByArgs['orderBy'] } : { orderBy?: Prisma.RequestDataroomGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.RequestDataroomGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.RequestDataroomGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.RequestDataroomGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.RequestDataroomGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.RequestDataroomGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/groupBy`, args, options, fetch);
}

export function useCountRequestDataroom<
  TArgs extends Prisma.RequestDataroomCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.RequestDataroomCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/count`, args, options, fetch);
}

export function useSuspenseCountRequestDataroom<
  TArgs extends Prisma.RequestDataroomCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.RequestDataroomCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestDataroomCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestDataroom', `${endpoint}/requestDataroom/count`, args, options, fetch);
}

export function useCheckRequestDataroom<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { createdBy?: string; updatedBy?: string; tenantId?: string; id?: string; requestId?: string; dataroomId?: string } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('RequestDataroom', `${endpoint}/requestDataroom/check`, args, options, fetch);
}
