/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, RequestHierarchy } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateRequestHierarchy(options?: Omit<(UseMutationOptions<(RequestHierarchy | undefined), DefaultError, Prisma.RequestHierarchyCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyCreateArgs, DefaultError, RequestHierarchy, true>('RequestHierarchy', 'POST', `${endpoint}/requestHierarchy/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyRequestHierarchy(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestHierarchyCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('RequestHierarchy', 'POST', `${endpoint}/requestHierarchy/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findMany`, args, options, fetch);
}

export function useInfiniteFindManyRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findMany`, args, options, fetch);
}

export function useSuspenseFindManyRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindManyArgs, TQueryFnData = Array<Prisma.RequestHierarchyGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findMany`, args, options, fetch);
}

export function useFindUniqueRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindUniqueArgs, TQueryFnData = Prisma.RequestHierarchyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindUniqueArgs, TQueryFnData = Prisma.RequestHierarchyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findUnique`, args, options, fetch);
}

export function useFindFirstRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindFirstArgs, TQueryFnData = Prisma.RequestHierarchyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstRequestHierarchy<TArgs extends Prisma.RequestHierarchyFindFirstArgs, TQueryFnData = Prisma.RequestHierarchyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/findFirst`, args, options, fetch);
}

export function useUpdateRequestHierarchy(options?: Omit<(UseMutationOptions<(RequestHierarchy | undefined), DefaultError, Prisma.RequestHierarchyUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyUpdateArgs, DefaultError, RequestHierarchy, true>('RequestHierarchy', 'PUT', `${endpoint}/requestHierarchy/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyRequestHierarchy(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestHierarchyUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('RequestHierarchy', 'PUT', `${endpoint}/requestHierarchy/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertRequestHierarchy(options?: Omit<(UseMutationOptions<(RequestHierarchy | undefined), DefaultError, Prisma.RequestHierarchyUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyUpsertArgs, DefaultError, RequestHierarchy, true>('RequestHierarchy', 'POST', `${endpoint}/requestHierarchy/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteRequestHierarchy(options?: Omit<(UseMutationOptions<(RequestHierarchy | undefined), DefaultError, Prisma.RequestHierarchyDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyDeleteArgs, DefaultError, RequestHierarchy, true>('RequestHierarchy', 'DELETE', `${endpoint}/requestHierarchy/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, RequestHierarchy, Prisma.RequestHierarchyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyRequestHierarchy(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.RequestHierarchyDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.RequestHierarchyDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('RequestHierarchy', 'DELETE', `${endpoint}/requestHierarchy/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.RequestHierarchyDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.RequestHierarchyDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.RequestHierarchyDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateRequestHierarchy<TArgs extends Prisma.RequestHierarchyAggregateArgs, TQueryFnData = Prisma.GetRequestHierarchyAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateRequestHierarchy<TArgs extends Prisma.RequestHierarchyAggregateArgs, TQueryFnData = Prisma.GetRequestHierarchyAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/aggregate`, args, options, fetch);
}

export function useGroupByRequestHierarchy<TArgs extends Prisma.RequestHierarchyGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.RequestHierarchyGroupByArgs['orderBy'] } : { orderBy?: Prisma.RequestHierarchyGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.RequestHierarchyGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.RequestHierarchyGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.RequestHierarchyGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByRequestHierarchy<TArgs extends Prisma.RequestHierarchyGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.RequestHierarchyGroupByArgs['orderBy'] } : { orderBy?: Prisma.RequestHierarchyGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.RequestHierarchyGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.RequestHierarchyGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.RequestHierarchyGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.RequestHierarchyGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/groupBy`, args, options, fetch);
}

export function useCountRequestHierarchy<TArgs extends Prisma.RequestHierarchyCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.RequestHierarchyCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/count`, args, options, fetch);
}

export function useSuspenseCountRequestHierarchy<TArgs extends Prisma.RequestHierarchyCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.RequestHierarchyCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.RequestHierarchyCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/count`, args, options, fetch);
}

export function useCheckRequestHierarchy<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; description?: string; createdBy?: string; modifiedBy?: string; tenantId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('RequestHierarchy', `${endpoint}/requestHierarchy/check`, args, options, fetch);
}
