/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import type { Prisma, SentEmail } from '../../../../node_modules/.prisma/client';
import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateSentEmail(options?: Omit<UseMutationOptions<SentEmail | undefined, DefaultError, Prisma.SentEmailCreateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.SentEmailCreateArgs, DefaultError, SentEmail, true>('SentEmail', 'POST', `${endpoint}/sentEmail/create`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.SentEmailCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.SentEmailCreateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.SentEmailCreateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManySentEmail(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SentEmailCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.SentEmailCreateManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'SentEmail',
    'POST',
    `${endpoint}/sentEmail/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.SentEmailCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.SentEmailCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SentEmailCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManySentEmail<
  TArgs extends Prisma.SentEmailFindManyArgs,
  TQueryFnData = Array<Prisma.SentEmailGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findMany`, args, options, fetch);
}

export function useInfiniteFindManySentEmail<TArgs extends Prisma.SentEmailFindManyArgs, TQueryFnData = Array<Prisma.SentEmailGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindManyArgs>,
  options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findMany`, args, options, fetch);
}

export function useSuspenseFindManySentEmail<
  TArgs extends Prisma.SentEmailFindManyArgs,
  TQueryFnData = Array<Prisma.SentEmailGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManySentEmail<TArgs extends Prisma.SentEmailFindManyArgs, TQueryFnData = Array<Prisma.SentEmailGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findMany`, args, options, fetch);
}

export function useFindUniqueSentEmail<
  TArgs extends Prisma.SentEmailFindUniqueArgs,
  TQueryFnData = Prisma.SentEmailGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindUniqueArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueSentEmail<
  TArgs extends Prisma.SentEmailFindUniqueArgs,
  TQueryFnData = Prisma.SentEmailGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findUnique`, args, options, fetch);
}

export function useFindFirstSentEmail<
  TArgs extends Prisma.SentEmailFindFirstArgs,
  TQueryFnData = Prisma.SentEmailGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindFirstArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstSentEmail<
  TArgs extends Prisma.SentEmailFindFirstArgs,
  TQueryFnData = Prisma.SentEmailGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/findFirst`, args, options, fetch);
}

export function useUpdateSentEmail(options?: Omit<UseMutationOptions<SentEmail | undefined, DefaultError, Prisma.SentEmailUpdateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.SentEmailUpdateArgs, DefaultError, SentEmail, true>('SentEmail', 'PUT', `${endpoint}/sentEmail/update`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.SentEmailUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.SentEmailUpdateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.SentEmailUpdateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManySentEmail(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SentEmailUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.SentEmailUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('SentEmail', 'PUT', `${endpoint}/sentEmail/updateMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.SentEmailUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.SentEmailUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SentEmailUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertSentEmail(options?: Omit<UseMutationOptions<SentEmail | undefined, DefaultError, Prisma.SentEmailUpsertArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.SentEmailUpsertArgs, DefaultError, SentEmail, true>('SentEmail', 'POST', `${endpoint}/sentEmail/upsert`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.SentEmailUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.SentEmailUpsertArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.SentEmailUpsertArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteSentEmail(options?: Omit<UseMutationOptions<SentEmail | undefined, DefaultError, Prisma.SentEmailDeleteArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.SentEmailDeleteArgs, DefaultError, SentEmail, true>('SentEmail', 'DELETE', `${endpoint}/sentEmail/delete`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.SentEmailDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.SentEmailDeleteArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.SentEmailDeleteArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, SentEmail, Prisma.SentEmailGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManySentEmail(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SentEmailDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.SentEmailDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>(
    'SentEmail',
    'DELETE',
    `${endpoint}/sentEmail/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.SentEmailDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.SentEmailDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SentEmailDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateSentEmail<TArgs extends Prisma.SentEmailAggregateArgs, TQueryFnData = Prisma.GetSentEmailAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.SentEmailAggregateArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateSentEmail<TArgs extends Prisma.SentEmailAggregateArgs, TQueryFnData = Prisma.GetSentEmailAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.SentEmailAggregateArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/aggregate`, args, options, fetch);
}

export function useGroupBySentEmail<
  TArgs extends Prisma.SentEmailGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.SentEmailGroupByArgs['orderBy'] } : { orderBy?: Prisma.SentEmailGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.SentEmailGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.SentEmailGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.SentEmailGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.SentEmailGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.SentEmailGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/groupBy`, args, options, fetch);
}

export function useSuspenseGroupBySentEmail<
  TArgs extends Prisma.SentEmailGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.SentEmailGroupByArgs['orderBy'] } : { orderBy?: Prisma.SentEmailGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.SentEmailGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.SentEmailGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.SentEmailGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.SentEmailGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.SentEmailGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/groupBy`, args, options, fetch);
}

export function useCountSentEmail<
  TArgs extends Prisma.SentEmailCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.SentEmailCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/count`, args, options, fetch);
}

export function useSuspenseCountSentEmail<
  TArgs extends Prisma.SentEmailCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.SentEmailCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.SentEmailCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('SentEmail', `${endpoint}/sentEmail/count`, args, options, fetch);
}

export function useCheckSentEmail<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { createdBy?: string; updatedBy?: string; tenantId?: string; id?: string; type?: string; recipient?: string; marketing?: boolean; domainSlug?: string } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('SentEmail', `${endpoint}/sentEmail/check`, args, options, fetch);
}
