/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { Prisma, Tenant } from '@zenstackhq/runtime/models';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateTenant(options?: Omit<UseMutationOptions<Tenant | undefined, DefaultError, Prisma.TenantCreateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.TenantCreateArgs, DefaultError, Tenant, true>('Tenant', 'POST', `${endpoint}/tenant/create`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.TenantCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.TenantCreateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.TenantCreateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyTenant(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TenantCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.TenantCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Tenant', 'POST', `${endpoint}/tenant/createMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.TenantCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.TenantCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TenantCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyTenant<
  TArgs extends Prisma.TenantFindManyArgs,
  TQueryFnData = Array<Prisma.TenantGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.TenantFindManyArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTenant<TArgs extends Prisma.TenantFindManyArgs, TQueryFnData = Array<Prisma.TenantGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.TenantFindManyArgs>,
  options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTenant<
  TArgs extends Prisma.TenantFindManyArgs,
  TQueryFnData = Array<Prisma.TenantGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.TenantFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTenant<TArgs extends Prisma.TenantFindManyArgs, TQueryFnData = Array<Prisma.TenantGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.TenantFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findMany`, args, options, fetch);
}

export function useFindUniqueTenant<TArgs extends Prisma.TenantFindUniqueArgs, TQueryFnData = Prisma.TenantGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.TenantFindUniqueArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTenant<
  TArgs extends Prisma.TenantFindUniqueArgs,
  TQueryFnData = Prisma.TenantGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.TenantFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findUnique`, args, options, fetch);
}

export function useFindFirstTenant<TArgs extends Prisma.TenantFindFirstArgs, TQueryFnData = Prisma.TenantGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.TenantFindFirstArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTenant<
  TArgs extends Prisma.TenantFindFirstArgs,
  TQueryFnData = Prisma.TenantGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.TenantFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/findFirst`, args, options, fetch);
}

export function useUpdateTenant(options?: Omit<UseMutationOptions<Tenant | undefined, DefaultError, Prisma.TenantUpdateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.TenantUpdateArgs, DefaultError, Tenant, true>('Tenant', 'PUT', `${endpoint}/tenant/update`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.TenantUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.TenantUpdateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.TenantUpdateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyTenant(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TenantUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.TenantUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Tenant', 'PUT', `${endpoint}/tenant/updateMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.TenantUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.TenantUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TenantUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertTenant(options?: Omit<UseMutationOptions<Tenant | undefined, DefaultError, Prisma.TenantUpsertArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.TenantUpsertArgs, DefaultError, Tenant, true>('Tenant', 'POST', `${endpoint}/tenant/upsert`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.TenantUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.TenantUpsertArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.TenantUpsertArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteTenant(options?: Omit<UseMutationOptions<Tenant | undefined, DefaultError, Prisma.TenantDeleteArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.TenantDeleteArgs, DefaultError, Tenant, true>('Tenant', 'DELETE', `${endpoint}/tenant/delete`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.TenantDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.TenantDeleteArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.TenantDeleteArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Tenant, Prisma.TenantGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyTenant(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TenantDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.TenantDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Tenant', 'DELETE', `${endpoint}/tenant/deleteMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.TenantDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.TenantDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TenantDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateTenant<TArgs extends Prisma.TenantAggregateArgs, TQueryFnData = Prisma.GetTenantAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.TenantAggregateArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTenant<TArgs extends Prisma.TenantAggregateArgs, TQueryFnData = Prisma.GetTenantAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.TenantAggregateArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/aggregate`, args, options, fetch);
}

export function useGroupByTenant<
  TArgs extends Prisma.TenantGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TenantGroupByArgs['orderBy'] } : { orderBy?: Prisma.TenantGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.TenantGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.TenantGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.TenantGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.TenantGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TenantGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTenant<
  TArgs extends Prisma.TenantGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TenantGroupByArgs['orderBy'] } : { orderBy?: Prisma.TenantGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.TenantGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.TenantGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.TenantGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.TenantGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TenantGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/groupBy`, args, options, fetch);
}

export function useCountTenant<
  TArgs extends Prisma.TenantCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TenantCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.TenantCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/count`, args, options, fetch);
}

export function useSuspenseCountTenant<
  TArgs extends Prisma.TenantCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TenantCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.TenantCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Tenant', `${endpoint}/tenant/count`, args, options, fetch);
}

export function useCheckTenant<TError = DefaultError>(
  args: {
    operation: PolicyCrudKind;
    where?: {
      createdBy?: string;
      updatedBy?: string;
      id?: string;
      name?: string;
      slug?: string;
      metadata?: string;
      logo?: string;
      websiteUrl?: string;
      title?: string;
      description?: string;
      primaryColor?: string;
      secondaryColor?: string;
      contactEmail?: string;
      contactPhone?: string;
      address?: string;
    };
  },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('Tenant', `${endpoint}/tenant/check`, args, options, fetch);
}
