/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { InfiniteData, UseInfiniteQueryOptions, UseMutationOptions, UseQueryOptions, UseSuspenseInfiniteQueryOptions, UseSuspenseQueryOptions } from '@tanstack/react-query';
import type { PolicyCrudKind } from '@zenstackhq/runtime';
import type { Prisma, Theme } from '@zenstackhq/runtime/models';
import type { CheckSelect, ExtraMutationOptions, ExtraQueryOptions, PickEnumerable, QueryError } from '@zenstackhq/tanstack-query/runtime-v5';
import { getHooksContext, useInfiniteModelQuery, useModelMutation, useModelQuery, useSuspenseInfiniteModelQuery, useSuspenseModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';

import metadata from './__model_meta';

type DefaultError = QueryError;

export function useCreateTheme(options?: Omit<UseMutationOptions<Theme | undefined, DefaultError, Prisma.ThemeCreateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ThemeCreateArgs, DefaultError, Theme, true>('Theme', 'POST', `${endpoint}/theme/create`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ThemeCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.ThemeCreateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.ThemeCreateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useCreateManyTheme(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ThemeCreateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ThemeCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Theme', 'POST', `${endpoint}/theme/createMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ThemeCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.ThemeCreateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ThemeCreateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManyTheme<TArgs extends Prisma.ThemeFindManyArgs, TQueryFnData = Array<Prisma.ThemeGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.ThemeFindManyArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTheme<TArgs extends Prisma.ThemeFindManyArgs, TQueryFnData = Array<Prisma.ThemeGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.ThemeFindManyArgs>,
  options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTheme<
  TArgs extends Prisma.ThemeFindManyArgs,
  TQueryFnData = Array<Prisma.ThemeGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ThemeFindManyArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTheme<TArgs extends Prisma.ThemeFindManyArgs, TQueryFnData = Array<Prisma.ThemeGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.ThemeFindManyArgs>,
  options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findMany`, args, options, fetch);
}

export function useFindUniqueTheme<TArgs extends Prisma.ThemeFindUniqueArgs, TQueryFnData = Prisma.ThemeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.ThemeFindUniqueArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTheme<
  TArgs extends Prisma.ThemeFindUniqueArgs,
  TQueryFnData = Prisma.ThemeGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args: Prisma.SelectSubset<TArgs, Prisma.ThemeFindUniqueArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findUnique`, args, options, fetch);
}

export function useFindFirstTheme<TArgs extends Prisma.ThemeFindFirstArgs, TQueryFnData = Prisma.ThemeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(
  args?: Prisma.SelectSubset<TArgs, Prisma.ThemeFindFirstArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTheme<
  TArgs extends Prisma.ThemeFindFirstArgs,
  TQueryFnData = Prisma.ThemeGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ThemeFindFirstArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/findFirst`, args, options, fetch);
}

export function useUpdateTheme(options?: Omit<UseMutationOptions<Theme | undefined, DefaultError, Prisma.ThemeUpdateArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ThemeUpdateArgs, DefaultError, Theme, true>('Theme', 'PUT', `${endpoint}/theme/update`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ThemeUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.ThemeUpdateArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.ThemeUpdateArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useUpdateManyTheme(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ThemeUpdateManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ThemeUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Theme', 'PUT', `${endpoint}/theme/updateMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ThemeUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.ThemeUpdateManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ThemeUpdateManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertTheme(options?: Omit<UseMutationOptions<Theme | undefined, DefaultError, Prisma.ThemeUpsertArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ThemeUpsertArgs, DefaultError, Theme, true>('Theme', 'POST', `${endpoint}/theme/upsert`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ThemeUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.ThemeUpsertArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.ThemeUpsertArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteTheme(options?: Omit<UseMutationOptions<Theme | undefined, DefaultError, Prisma.ThemeDeleteArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ThemeDeleteArgs, DefaultError, Theme, true>('Theme', 'DELETE', `${endpoint}/theme/delete`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ThemeDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.ThemeDeleteArgs>,
      options?: Omit<
        UseMutationOptions<CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined, DefaultError, Prisma.SelectSubset<T, Prisma.ThemeDeleteArgs>> & ExtraMutationOptions,
        'mutationFn'
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as CheckSelect<T, Theme, Prisma.ThemeGetPayload<T>> | undefined;
    },
  };
  return mutation;
}

export function useDeleteManyTheme(options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ThemeDeleteManyArgs> & ExtraMutationOptions, 'mutationFn'>) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<Prisma.ThemeDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Theme', 'DELETE', `${endpoint}/theme/deleteMany`, metadata, options, fetch, false);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.ThemeDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.ThemeDeleteManyArgs>,
      options?: Omit<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ThemeDeleteManyArgs>> & ExtraMutationOptions, 'mutationFn'>
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateTheme<TArgs extends Prisma.ThemeAggregateArgs, TQueryFnData = Prisma.GetThemeAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.ThemeAggregateArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTheme<TArgs extends Prisma.ThemeAggregateArgs, TQueryFnData = Prisma.GetThemeAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(
  args: Prisma.SelectSubset<TArgs, Prisma.ThemeAggregateArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/aggregate`, args, options, fetch);
}

export function useGroupByTheme<
  TArgs extends Prisma.ThemeGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ThemeGroupByArgs['orderBy'] } : { orderBy?: Prisma.ThemeGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.ThemeGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.ThemeGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.ThemeGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.ThemeGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ThemeGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTheme<
  TArgs extends Prisma.ThemeGroupByArgs,
  HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>,
  OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ThemeGroupByArgs['orderBy'] } : { orderBy?: Prisma.ThemeGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.ThemeGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs & keyof Prisma.ThemeGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.ThemeGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.ThemeGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ThemeGroupByArgs, OrderByArg> & InputErrors>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/groupBy`, args, options, fetch);
}

export function useCountTheme<
  TArgs extends Prisma.ThemeCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ThemeCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ThemeCountArgs>, options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/count`, args, options, fetch);
}

export function useSuspenseCountTheme<
  TArgs extends Prisma.ThemeCountArgs,
  TQueryFnData = TArgs extends { select: any } ? (TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ThemeCountAggregateOutputType>) : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(args?: Prisma.SelectSubset<TArgs, Prisma.ThemeCountArgs>, options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>('Theme', `${endpoint}/theme/count`, args, options, fetch);
}

export function useCheckTheme<TError = DefaultError>(
  args: { operation: PolicyCrudKind; where?: { id?: string; userId?: string; name?: string; styles?: string } },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>('Theme', `${endpoint}/theme/check`, args, options, fetch);
}
