import type { Metadata } from 'next';
import { AppSidebar } from '@/components/@Admin/Layout/app-sidebar';
import { ModeToggle } from '@/components/@Admin/Layout/mode-toogle';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="flex h-screen w-full flex-1 flex-col gap-4 p-4 pt-0">
        <div className="flex items-center gap-3">
          <SidebarTrigger />
          <ModeToggle />
        </div>
        {children}
      </main>
    </SidebarProvider>
  );
}
