import { Prisma, PrismaClient } from '@prisma/client';
import { DefaultArgs } from '@prisma/client/runtime/library';

import { generateUuid, UNSTABLE_TENANT_ID, type AssignmentCategoryInput } from '../util';

export async function createCreditosArea(
  prisma: PrismaClient<Prisma.PrismaClientOptions, never, DefaultArgs>,
  hierarchyId: string,
  hierarchyLevelRequestTypeId: string,
  hierarchyLevelCategoryId: string,
  hierarchyLevelSubcategoryId: string
) {
  const areaId = generateUuid();
  const tenantId = UNSTABLE_TENANT_ID;

  const assignmentCategories: AssignmentCategoryInput[] = [
    {
      name: 'Consulta',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicion Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Baja De Migracion',
          description: '',
          subcategories: [{ name: 'Baja De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth ', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Activar Desde El Facturador',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth ', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Agregar Servicios Moviles',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth ', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Agregar Numero Favorito',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth ', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Cambio Razon Social',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Correccion De Nombre',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Validacion Financiamientos Equipos De Alto Valor',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Solicitudes Bloqueadas De Claro Altas',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
    {
      name: 'Solicitud',
      description: '',
      subcategories: [
        {
          name: 'Multimedia',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Pospago',
          description: '',
          subcategories: [
            { name: 'Autorizacion Por Tercer Venta', description: '' },
            { name: 'Cliente Segmento Nuevo', description: '' },
            { name: 'Cliente Desactivo', description: '' },
            { name: 'Cliente Incobrables', description: '' },
            { name: 'Cliente Extrajero', description: '' },
            { name: 'Excedente En Limite De Compra', description: '' },
            { name: 'Empaquetamiento', description: '' },
            { name: 'Renovacion', description: '' },
            { name: 'Segmentacion De Cliente', description: '' },
            { name: 'Sesion De Derecho', description: '' },
            { name: 'Validacion De Soporte De Ingresos', description: '' },
            { name: 'Validacion De Limite De Compra', description: '' },
            { name: 'Validaciones Para Entrega Terminaes', description: '' },
            { name: 'Validacion Problemas Sistema', description: '' },
            { name: 'Apoyo Posventa', description: '' },
            { name: 'Solicitudes Bloqueadas', description: '' },
          ],
        },
        {
          name: 'Activacion',
          description: '',
          subcategories: [{ name: 'Activacion', description: '' }],
        },
        {
          name: 'Modificaciones',
          description: '',
          subcategories: [
            { name: 'Activacion De Servicios Suplementarios', description: '' },
            { name: 'Baja Por Migracion De Servicios', description: '' },
            { name: 'Cambio Razon Social / Actualizacion De Datos', description: '' },
            { name: 'Cambio De Variable / Empaquetamientos', description: '' },
            { name: 'Correccion De Servicio', description: '' },
            { name: 'Anulacion De Solicitud De Venta Por Mal Registro', description: '' },
            { name: 'Adicion De Numero Favorito Lda', description: '' },
            { name: 'Adicion / Retiro De Paquetes De Canales', description: '' },
            { name: 'Cambio De Direccion', description: '' },
            { name: 'Correccion / Cambio De Direccion', description: '' },
          ],
        },
        {
          name: 'Bajas De Migracion',
          description: '',
          subcategories: [{ name: 'Bajas De Migracion', description: '' }],
        },
        {
          name: 'Sistemas',
          description: '',
          subcategories: [
            { name: 'Creacion De Accesos', description: '' },
            { name: 'Baja De Accesos', description: '' },
            { name: 'Cambio', description: '' },
            { name: 'Claro Altas', description: '' },
            { name: 'Reinicio De Contraseña Altas', description: '' },
            { name: 'Reinicio De Contraseña Docflow', description: '' },
            { name: 'Reinicio De Contraseña Syrem Ventas', description: '' },
            { name: 'Reinicio De Contraseña Helpdesk', description: '' },
          ],
        },
        {
          name: 'Reactivaciones',
          description: '',
          subcategories: [
            { name: 'Dth', description: '' },
            { name: 'Pospago', description: '' },
            { name: 'Casa Claro', description: '' },
            { name: 'Desbloqueo De Modem', description: '' },
          ],
        },
        {
          name: 'Multas',
          description: '',
          subcategories: [
            { name: 'Multimedia', description: '' },
            { name: 'Pospago', description: '' },
          ],
        },
      ],
    },
  ];

  const assignmentCategoryData = assignmentCategories.map((category) => ({
    name: category.name,
    description: category.description,
    tenantId,
    hierarchyId,
    hierarchyLevelId: hierarchyLevelRequestTypeId,
    subcategories: {
      create: category.subcategories?.map((subcategory) => ({
        name: subcategory.name,
        description: subcategory.description,
        tenantId,
        hierarchyId,
        hierarchyLevelId: hierarchyLevelCategoryId,
        areaId,
        subcategories: {
          create: subcategory.subcategories?.map((subSubcategory) => ({
            name: subSubcategory.name,
            description: subSubcategory.description,
            tenantId,
            hierarchyId,
            hierarchyLevelId: hierarchyLevelSubcategoryId,
            areaId,
          })),
        },
      })),
    },
  }));

  return await prisma.area.create({
    data: {
      id: areaId,
      name: 'Creditos',
      description: '',
      tenantId,
      assignmentCategories: {
        create: assignmentCategoryData,
      },
    },
  });
}
