/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from '@zenstackhq/runtime/zod/input';

import { db } from '.';
import { createTRPCRouter, procedure } from '../../trpc';
import { checkMutate, checkRead } from '../helper';

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure.input($Schema.FeatureInputSchema.aggregate).query(({ ctx, input }) => checkRead(db(ctx).feature.aggregate(input as any))),

    createMany: procedure.input($Schema.FeatureInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).feature.createMany(input as any))),

    create: procedure.input($Schema.FeatureInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).feature.create(input as any))),

    deleteMany: procedure.input($Schema.FeatureInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).feature.deleteMany(input as any))),

    delete: procedure.input($Schema.FeatureInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).feature.delete(input as any))),

    findFirst: procedure.input($Schema.FeatureInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).feature.findFirst(input as any))),

    findFirstOrThrow: procedure.input($Schema.FeatureInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).feature.findFirstOrThrow(input as any))),

    findMany: procedure.input($Schema.FeatureInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).feature.findMany(input as any))),

    findUnique: procedure.input($Schema.FeatureInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).feature.findUnique(input as any))),

    findUniqueOrThrow: procedure.input($Schema.FeatureInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).feature.findUniqueOrThrow(input as any))),

    groupBy: procedure.input($Schema.FeatureInputSchema.groupBy).query(({ ctx, input }) => checkRead(db(ctx).feature.groupBy(input as any))),

    updateMany: procedure.input($Schema.FeatureInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).feature.updateMany(input as any))),

    update: procedure.input($Schema.FeatureInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).feature.update(input as any))),

    upsert: procedure.input($Schema.FeatureInputSchema.upsert).mutation(async ({ ctx, input }) => checkMutate(db(ctx).feature.upsert(input as any))),

    count: procedure.input($Schema.FeatureInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).feature.count(input as any))),
  });
}
