/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from '@zenstackhq/runtime/zod/input';

import { db } from '.';
import { createTRPCRouter, procedure } from '../../trpc';
import { checkMutate, checkRead } from '../helper';

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure.input($Schema.RoleFeatureInputSchema.aggregate).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.aggregate(input as any))),

    createMany: procedure.input($Schema.RoleFeatureInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).roleFeature.createMany(input as any))),

    create: procedure.input($Schema.RoleFeatureInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).roleFeature.create(input as any))),

    deleteMany: procedure.input($Schema.RoleFeatureInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).roleFeature.deleteMany(input as any))),

    delete: procedure.input($Schema.RoleFeatureInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).roleFeature.delete(input as any))),

    findFirst: procedure.input($Schema.RoleFeatureInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.findFirst(input as any))),

    findFirstOrThrow: procedure.input($Schema.RoleFeatureInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.findFirstOrThrow(input as any))),

    findMany: procedure.input($Schema.RoleFeatureInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.findMany(input as any))),

    findUnique: procedure.input($Schema.RoleFeatureInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.findUnique(input as any))),

    findUniqueOrThrow: procedure.input($Schema.RoleFeatureInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.findUniqueOrThrow(input as any))),

    groupBy: procedure.input($Schema.RoleFeatureInputSchema.groupBy).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.groupBy(input as any))),

    updateMany: procedure.input($Schema.RoleFeatureInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).roleFeature.updateMany(input as any))),

    update: procedure.input($Schema.RoleFeatureInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).roleFeature.update(input as any))),

    upsert: procedure.input($Schema.RoleFeatureInputSchema.upsert).mutation(async ({ ctx, input }) => checkMutate(db(ctx).roleFeature.upsert(input as any))),

    count: procedure.input($Schema.RoleFeatureInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).roleFeature.count(input as any))),
  });
}
